server:
  port: 2020
  context-path: /
  tomcat:
    uri-encoding: UTF-8


spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 10MB


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml